import { useCallback, useEffect, useState } from 'react';
import api from '../lib/api';
import { Shell } from './Dashboard';
const initial={name:'',license_number:'',license_category:'Heavy',license_expiry_date:'',contact_number:'',safety_score:'100'};
export default function Drivers({role}){
 const [drivers,setDrivers]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[form,setForm]=useState(initial),[saving,setSaving]=useState(false),[query,setQuery]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get('/drivers');setDrivers(r.data)}catch(e){setError(e.response?.data?.error||'Failed to load drivers.')}finally{setLoading(false)}},[]); useEffect(()=>{load()},[load]);
 const submit=async(e)=>{e.preventDefault();setSaving(true);try{await api.post('/drivers',{...form,safety_score:Number(form.safety_score)});setShow(false);setForm(initial);load()}catch(e){setError(e.response?.data?.error||'Could not register driver.')}finally{setSaving(false)}};
 const visible=drivers.filter(d=>`${d.name} ${d.license_number}`.toLowerCase().includes(query.toLowerCase()));
 return <Shell role={role} onLogout={()=>{localStorage.clear();location.href='/login'}} title="Drivers" subtitle="Driver registry, safety and availability"><div className="page-heading"><div><h1>Driver Management</h1><p>Monitor licenses, safety scores and driver availability.</p></div>{(role==='Fleet Manager'||role==='Safety Officer')&&<button className="primary-btn" onClick={()=>setShow(true)}>＋ Add driver</button>}</div>{error&&<div className="alert error-alert">{error}<button onClick={load}>Retry</button></div>}<div className="toolbar"><input placeholder="Search drivers…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="secondary-btn" onClick={load}>↻ Refresh</button></div><div className="panel table-panel">{loading?<div className="loading">Loading drivers…</div>:<table className="data-table"><thead><tr><th>Driver</th><th>License</th><th>Safety score</th><th>Contact</th><th>Status</th></tr></thead><tbody>{visible.map(d=><tr key={d.id}><td className="table-primary">{d.name}</td><td>{d.license_number}<div className="muted">{d.license_category} · exp. {d.license_expiry_date?.slice(0,10)}</div></td><td><span className={`score ${d.safety_score>=80?'good':d.safety_score>=50?'warn':'bad'}`}>{d.safety_score}/100</span></td><td>{d.contact_number||'—'}</td><td><span className="status-badge">{d.status}</span></td></tr>)}{!drivers.length&&<tr><td colSpan="5" className="loading">No drivers registered.</td></tr>}</tbody></table>}</div>{show&&<div className="modal-backdrop"><div className="modal"><div className="modal-header"><h2>Register driver</h2><button className="close-btn" onClick={()=>setShow(false)}>×</button></div><form onSubmit={submit}><div className="form-grid">{[['name','Full name'],['license_number','License number'],['license_category','License category'],['license_expiry_date','License expiry'],['contact_number','Contact number'],['safety_score','Safety score']].map(([k,l])=><label className="form-stack" key={k}>{l}<input required={['name','license_number','license_expiry_date'].includes(k)} type={k==='license_expiry_date'?'date':k==='safety_score'?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setShow(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':'Register driver'}</button></div></form></div></div>}</Shell>
}
